services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'

  web1:
    build: ./web
    image: 869588908060.dkr.ecr.ap-south-1.amazonaws.com/my-app:web1-${GITHUB_SHA}
    restart: on-failure
    hostname: web1
    ports:
      - '81:5000'

  web2:
    build: ./web
    image: 869588908060.dkr.ecr.ap-south-1.amazonaws.com/my-app:web2-${GITHUB_SHA}
    restart: on-failure
    hostname: web2
    ports:
      - '82:5000'

  nginx:
    build: ./nginx
    image: 869588908060.dkr.ecr.ap-south-1.amazonaws.com/my-app:nginx-${GITHUB_SHA}
    ports:
      - '80:80'
    depends_on:
      - web1
      - web2
