services:

 #Redis service acts as in-memory database/cache
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
      
  #web1 is the first instance of the Node.js application(used for load balancing with nginx)
  web1:
    build: ./web
    image: capstone1.azurecr.io/capstone-web:${TAG_VALUE:-latest}
    restart: on-failure
    hostname: web1
    ports:
      - '81:5000'
      
  #web2 is the second instance of the Node.js application(used for load balancing with nginx)
  web2:
    build: ./web
    image: capstone1.azurecr.io/capstone-web:${TAG_VALUE:-latest}
    restart: on-failure
    hostname: web2
    ports:
      - '82:5000'

  #nginx reverse proxy / load balance: Routes traffic to web1 and web2 instances
  nginx:
    build: ./nginx
    image: capstone1.azurecr.io/capstone-nginx:${TAG_VALUE:-latest}
    ports:
      - '80:80'
    depends_on:
      - web1
      - web2
