name: Multi-Stage CI/CD Pipeline

#Trigger pipeline when code is pushed to the main branch
on:
  push:
    branches:
      - main

#Creeating global environment variables 
env:
  ECR_REPOSITORY: capstone-project/capstone-repo
  AWS_REGION: ap-south-1
  TAG_VALUE: ${{ github.sha }}

jobs:

   #Build and Push docker images to AWS ECR--build stage
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
        #Pull the latest code from repository
      - name: Checkout Code
        uses: actions/checkout@v4

        #Configure AWS credentials from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

        #Authenticate Docker with AWS ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

       #Check if ECR repository exists;if not, create it
      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} || \
          aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }}

      # - name: Build images using Docker Compose
      #   uses: hoverkraft-tech/compose-action@3846bcd61da338e9eaaf83e7ed0234a12b099b72
      #   with:
      #     compose-file: "./compose.yml"

      # - name: Push images to ECR
      #   run: |
      #     docker compose -f ./compose.yml push
      
      #Build and push all Docker images using Docker Compose 
      - name: Build and Push all images using Docker Compose
        run: |
          docker compose -f ./compose.yaml build
          docker compose -f ./compose.yaml push

  #test stage
  docker-test:
    runs-on: ubuntu-latest
    needs: docker-build  #This job runs only afterdocker-build succeeds
    steps:

        #Pull code again on runner
      - name: Checkout Code
        uses: actions/checkout@v4

        #Start containers for testing
      - name: Start Containers for Testing
        run: docker compose -f ./compose.yaml up -d
        
        #Allow time for services to boot fully
      - name: Wait for Services to Start
        run: sleep 5

        #Run smoke tests
      - name: Run Smoke Test
        run: |
          chmod +x ./smoke-test.sh
          ./smoke-test.sh

        #Run integration tests
      - name: Run Integration Test
        run: |
          chmod +x ./integration-test.sh
          ./integration-test.sh

       #Remove containers after testing
      - name: Stop Test Containers
        run: docker compose -f ./compose.yaml down

#deploy stage
  docker-deploy:
    runs-on: ubuntu-latest
    needs: docker-test #this job runs only if docker-test succeds
    steps:
        #SSH into EC2 and execute deployment commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.INSTANCE1_IP }},${{ secrets.INSTANCE2_IP }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            #Login to ECR
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com
            
            #Create directory and clone repo 
            cd /home/ubuntu || mkdir -p /home/ubuntu && cd /home/ubuntu
            if [ ! -d "capstone_project" ]; then
              git clone https://github.com/SreejaPakkiru/Capstone_Project.git capstone_project
            fi
            cd capstone_project

            #Puling and run images via Docker Compose
            docker compose -f ./compose.yaml pull
            docker compose -f ./compose.yaml up -d --remove-orphans
